import funciones as fn

fn.sumarFijo()
print("SUMANDO")
nu1 = int(input("Ingrese número 1: "))
nu2 = int(input("Ingrese número 2: "))
resultado = fn.sumar(nu1,nu2)
print(resultado)
print("RESTANDO")
n1 = int(input("Ingrese número 1: "))
n2 = int(input("Ingrese número 2: "))
result = fn.resta(n1,n2)
print(result)
#print(pi)
print("CALCULANDO CÍRCULOS")
radio = float(input("Ingrese radio del círculo: "))
area = fn.areaCirculo(radio)
print("Area : ",area)
perim = fn.perimetroCirculo(radio)
print("Perímetro: ",perim)

